import { LenderProfile, LoanRequest } from "./types";

const avatarColors = [
  "#0D7C66", "#3B82F6", "#8B5CF6", "#EC4899",
  "#F59E0B", "#EF4444", "#06B6D4", "#84CC16",
];

function getInitials(name: string): string {
  return name.split(" ").map(n => n[0]).join("").toUpperCase();
}

export const seedLenders: LenderProfile[] = [
  {
    id: "lender_1",
    name: "Marcus Chen",
    initials: "MC",
    avatarColor: avatarColors[0],
    rating: 4.8,
    reviewCount: 142,
    interestRate: 5.5,
    minLoan: 100,
    maxLoan: 5000,
    repaymentDays: 30,
    totalLoansGiven: 312,
    totalAmountLent: 245000,
    verified: true,
    description: "Experienced microlender focused on small business funding. Fast approval, flexible terms.",
    joinDate: "2024-03-15",
    responseTime: "< 1 hour",
  },
  {
    id: "lender_2",
    name: "Sarah Williams",
    initials: "SW",
    avatarColor: avatarColors[1],
    rating: 4.9,
    reviewCount: 89,
    interestRate: 4.2,
    minLoan: 50,
    maxLoan: 3000,
    repaymentDays: 14,
    totalLoansGiven: 198,
    totalAmountLent: 156000,
    verified: true,
    description: "Quick-turnaround lender specializing in emergency funds. Lowest rates for repeat borrowers.",
    joinDate: "2024-01-20",
    responseTime: "< 30 min",
  },
  {
    id: "lender_3",
    name: "James Okafor",
    initials: "JO",
    avatarColor: avatarColors[2],
    rating: 4.6,
    reviewCount: 67,
    interestRate: 6.0,
    minLoan: 200,
    maxLoan: 10000,
    repaymentDays: 60,
    totalLoansGiven: 145,
    totalAmountLent: 520000,
    verified: true,
    description: "Large-amount lender for established borrowers. Longer terms available for qualified applicants.",
    joinDate: "2023-11-08",
    responseTime: "< 2 hours",
  },
  {
    id: "lender_4",
    name: "Amira Patel",
    initials: "AP",
    avatarColor: avatarColors[3],
    rating: 4.7,
    reviewCount: 203,
    interestRate: 3.8,
    minLoan: 25,
    maxLoan: 1500,
    repaymentDays: 7,
    totalLoansGiven: 510,
    totalAmountLent: 89000,
    verified: true,
    description: "Micro-loan specialist. Perfect for small, short-term needs. High approval rate.",
    joinDate: "2024-06-01",
    responseTime: "< 15 min",
  },
  {
    id: "lender_5",
    name: "Robert Kim",
    initials: "RK",
    avatarColor: avatarColors[4],
    rating: 4.5,
    reviewCount: 45,
    interestRate: 7.0,
    minLoan: 500,
    maxLoan: 15000,
    repaymentDays: 90,
    totalLoansGiven: 78,
    totalAmountLent: 680000,
    verified: true,
    description: "Premium lender for larger amounts. Extended repayment options. Business-focused lending.",
    joinDate: "2024-02-14",
    responseTime: "< 4 hours",
  },
  {
    id: "lender_6",
    name: "Elena Torres",
    initials: "ET",
    avatarColor: avatarColors[5],
    rating: 4.4,
    reviewCount: 112,
    interestRate: 5.0,
    minLoan: 100,
    maxLoan: 4000,
    repaymentDays: 45,
    totalLoansGiven: 234,
    totalAmountLent: 310000,
    verified: false,
    description: "Reliable lender with consistent terms. Good option for first-time borrowers.",
    joinDate: "2024-04-22",
    responseTime: "< 3 hours",
  },
  {
    id: "lender_7",
    name: "David Nakamura",
    initials: "DN",
    avatarColor: avatarColors[6],
    rating: 4.9,
    reviewCount: 178,
    interestRate: 4.5,
    minLoan: 75,
    maxLoan: 6000,
    repaymentDays: 30,
    totalLoansGiven: 401,
    totalAmountLent: 445000,
    verified: true,
    description: "Top-rated lender with competitive rates. Known for transparent terms and fast processing.",
    joinDate: "2023-09-10",
    responseTime: "< 45 min",
  },
];

export const seedLoans: LoanRequest[] = [
  {
    id: "loan_1",
    lenderId: "lender_2",
    lenderName: "Sarah Williams",
    borrowerName: "You",
    amount: 500,
    interestRate: 4.2,
    totalRepayment: 521,
    repaymentDays: 14,
    status: "active",
    requestDate: "2026-01-28",
    approvalDate: "2026-01-28",
    dueDate: "2026-02-11",
    amountPaid: 260,
    purpose: "Emergency car repair",
    payments: [
      { id: "pay_1", amount: 130, date: "2026-02-01" },
      { id: "pay_2", amount: 130, date: "2026-02-05" },
    ],
  },
  {
    id: "loan_2",
    lenderId: "lender_1",
    lenderName: "Marcus Chen",
    borrowerName: "You",
    amount: 1000,
    interestRate: 5.5,
    totalRepayment: 1055,
    repaymentDays: 30,
    status: "completed",
    requestDate: "2025-12-01",
    approvalDate: "2025-12-01",
    dueDate: "2025-12-31",
    amountPaid: 1055,
    purpose: "Business inventory",
    payments: [
      { id: "pay_3", amount: 350, date: "2025-12-10" },
      { id: "pay_4", amount: 355, date: "2025-12-20" },
      { id: "pay_5", amount: 350, date: "2025-12-30" },
    ],
  },
];

export const seedLenderLoans: LoanRequest[] = [
  {
    id: "loan_l1",
    lenderId: "lender_self",
    lenderName: "You",
    borrowerName: "Alex Johnson",
    amount: 750,
    interestRate: 5.0,
    totalRepayment: 787.5,
    repaymentDays: 30,
    status: "pending",
    requestDate: "2026-02-13",
    amountPaid: 0,
    purpose: "Medical expenses",
    payments: [],
  },
  {
    id: "loan_l2",
    lenderId: "lender_self",
    lenderName: "You",
    borrowerName: "Maria Santos",
    amount: 300,
    interestRate: 5.0,
    totalRepayment: 315,
    repaymentDays: 14,
    status: "pending",
    requestDate: "2026-02-12",
    amountPaid: 0,
    purpose: "Rent shortfall",
    payments: [],
  },
  {
    id: "loan_l3",
    lenderId: "lender_self",
    lenderName: "You",
    borrowerName: "Chris Lee",
    amount: 2000,
    interestRate: 5.0,
    totalRepayment: 2100,
    repaymentDays: 60,
    status: "active",
    requestDate: "2026-01-15",
    approvalDate: "2026-01-16",
    dueDate: "2026-03-16",
    amountPaid: 700,
    purpose: "Equipment purchase",
    payments: [
      { id: "pay_l1", amount: 350, date: "2026-01-30" },
      { id: "pay_l2", amount: 350, date: "2026-02-10" },
    ],
  },
  {
    id: "loan_l4",
    lenderId: "lender_self",
    lenderName: "You",
    borrowerName: "Priya Sharma",
    amount: 500,
    interestRate: 5.0,
    totalRepayment: 525,
    repaymentDays: 14,
    status: "completed",
    requestDate: "2025-12-20",
    approvalDate: "2025-12-20",
    dueDate: "2026-01-03",
    amountPaid: 525,
    purpose: "Holiday travel",
    payments: [
      { id: "pay_l3", amount: 262.5, date: "2025-12-27" },
      { id: "pay_l4", amount: 262.5, date: "2026-01-02" },
    ],
  },
];
